#!/bin/bash
# ============================================================
# Nexus — Decision Logger
# Auto-detects architectural decisions and generates ADR docs
# ============================================================

set -euo pipefail

NEXUS_HOME="${NEXUS_HOME:-$HOME/.nexus}"
REPO=$(basename "$(git rev-parse --show-toplevel 2>/dev/null)" 2>/dev/null || echo "unknown")
DECISIONS_DIR="$NEXUS_HOME/decisions/${REPO}"
mkdir -p "$DECISIONS_DIR"

# ── Helpers ───────────────────────────────────────────────

get_next_adr_num() {
  find "$DECISIONS_DIR" -name 'ADR-*.md' 2>/dev/null | wc -l | tr -d ' '
}

slugify() {
  echo "$1" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed 's/[^a-z0-9-]//g'
}

# ── Create ADR ────────────────────────────────────────────

create_adr() {
  local title="${1:-Untitled Decision}"
  local context="${2:-}"
  local decision="${3:-}"
  local alternatives="${4:-}"
  local impact="${5:-}"
  local ticket="${6:-}"

  local num
  num=$(($(get_next_adr_num) + 1))
  local slug
  slug=$(slugify "$title")
  local adr_file="$DECISIONS_DIR/ADR-$(printf '%04d' "$num")-${slug}.md"
  local author
  author=$(git config user.name 2>/dev/null || echo "unknown")
  local branch
  branch=$(git branch --show-current 2>/dev/null || echo "unknown")

  cat > "$adr_file" << ADREOF
# ADR-$(printf '%04d' "$num"): $title

| Field | Value |
|-------|-------|
| **Date** | $(date +%Y-%m-%d) |
| **Status** | proposed |
| **Author** | $author |
| **Branch** | $branch |
| **Related Ticket** | ${ticket:-N/A} |

## 1. Context

${context:-[To be completed]}

## 2. Decision

${decision:-[To be completed]}

## 3. Alternatives

| # | Option | Pros | Cons | Outcome |
|---|--------|------|------|---------|
| 1 | [Option A] | ... | ... | Selected |
| 2 | [Option B] | ... | ... | Rejected |
| 3 | [Option C] | ... | ... | Rejected |

${alternatives}

## 4. Impact

${impact:-[To be completed]}

## 5. Risks & Mitigations

| Risk | Severity | Mitigation |
|------|----------|------------|
| [Risk 1] | Medium | [How to mitigate] |

## 6. Related Links

- PR:
- Slack discussion:
- Related ADRs:
- Documentation:

---
*Generated by Claude Code + Nexus | $(date -u +%Y-%m-%dT%H:%M:%SZ)*
ADREOF

  echo "$adr_file"
}

# ── List ADRs ─────────────────────────────────────────────

list_adrs() {
  echo "Architecture Decision Records — $REPO"
  echo "======================================"

  if [ ! -d "$DECISIONS_DIR" ] || [ -z "$(ls -A "$DECISIONS_DIR" 2>/dev/null)" ]; then
    echo "  (no ADRs yet)"
    return
  fi

  for adr in "$DECISIONS_DIR"/ADR-*.md; do
    [ -f "$adr" ] || continue
    local filename=$(basename "$adr")
    local title
    title=$(head -3 "$adr" | grep '^# ' | sed 's/^# ADR-[0-9]*: //' | head -1)
    local status
    status=$(grep '\*\*Status\*\*' "$adr" | sed 's/.*| //' | head -1 || echo "unknown")
    local date
    date=$(grep '\*\*Date\*\*' "$adr" | sed 's/.*| //' | head -1 || echo "unknown")

    case "$status" in
      *accepted*)    local icon="[ACCEPTED]" ;;
      *proposed*)    local icon="[PROPOSED]" ;;
      *deprecated*)  local icon="[DEPRECATED]" ;;
      *superseded*)  local icon="[SUPERSEDED]" ;;
      *)             local icon="[UNKNOWN]" ;;
    esac

    echo "  $icon $filename — $title ($date)"
  done
}

# ── Search ADRs ───────────────────────────────────────────

search_adrs() {
  local query="${1:-}"
  if [ -z "$query" ]; then
    echo "Usage: decision-log search <keyword>"
    return
  fi

  echo "Searching ADRs for: \"$query\""
  echo "=============================="

  grep -ril "$query" "$DECISIONS_DIR" 2>/dev/null | while read -r adr; do
    local filename=$(basename "$adr")
    local title
    title=$(head -3 "$adr" | grep '^# ' | sed 's/^# ADR-[0-9]*: //' | head -1)
    echo ""
    echo "  $filename: $title"
    grep -i "$query" "$adr" | head -2 | sed 's/^/    -> /'
  done || echo "  (no matches)"
}

# ── Update status ─────────────────────────────────────────

update_status() {
  local adr_file="$1"
  local new_status="${2:-accepted}"

  if [ ! -f "$adr_file" ]; then
    echo "Error: ADR file not found: $adr_file"
    exit 1
  fi

  # Use sed -i with backup for cross-platform compatibility
  if sed --version 2>/dev/null | grep -q GNU; then
    sed -i "s/\*\*Status\*\* | .*/\*\*Status\*\* | $new_status/" "$adr_file"
  else
    sed -i '' "s/\*\*Status\*\* | .*/\*\*Status\*\* | $new_status/" "$adr_file"
  fi
  echo "Updated $(basename "$adr_file") status to: $new_status"
}

# ── Main ──────────────────────────────────────────────────

COMMAND="${1:-list}"

case "$COMMAND" in
  create)
    shift
    TITLE="${1:-}"
    if [ -z "$TITLE" ]; then
      echo "Usage: decision-log create <title> [context] [decision]"
      echo "Example: decision-log create 'Migrate session storage from Redis to JWT'"
      exit 1
    fi
    ADR_FILE=$(create_adr "$TITLE" "${2:-}" "${3:-}")
    echo "ADR created: $ADR_FILE"
    echo "Edit this file to add full details."
    ;;

  list)
    list_adrs
    ;;

  search)
    search_adrs "${2:-}"
    ;;

  status)
    update_status "${2:-}" "${3:-accepted}"
    ;;

  stats)
    echo "ADR Statistics — $REPO"
    echo "========================"
    total=$(find "$DECISIONS_DIR" -name 'ADR-*.md' 2>/dev/null | wc -l | tr -d ' ')
    proposed=$(grep -rl '\*\*Status\*\* | proposed' "$DECISIONS_DIR" 2>/dev/null | wc -l | tr -d ' ' || echo 0)
    accepted=$(grep -rl '\*\*Status\*\* | accepted' "$DECISIONS_DIR" 2>/dev/null | wc -l | tr -d ' ' || echo 0)
    deprecated=$(grep -rl '\*\*Status\*\* | deprecated' "$DECISIONS_DIR" 2>/dev/null | wc -l | tr -d ' ' || echo 0)
    superseded=$(grep -rl '\*\*Status\*\* | superseded' "$DECISIONS_DIR" 2>/dev/null | wc -l | tr -d ' ' || echo 0)

    echo "  Total:       $total"
    echo "  Accepted:    $accepted"
    echo "  Proposed:    $proposed"
    echo "  Deprecated:  $deprecated"
    echo "  Superseded:  $superseded"
    ;;

  *)
    echo "Nexus — Decision Logger"
    echo ""
    echo "Usage: decision-log <command> [args]"
    echo ""
    echo "Commands:"
    echo "  create <title>            Create a new ADR"
    echo "  list                      List all ADRs"
    echo "  search <keyword>          Search ADRs"
    echo "  status <file> <status>    Update ADR status"
    echo "  stats                     Show ADR statistics"
    ;;
esac
